### ISSUE TITLE
[suggestion] Add premium player support

### ISSUE THREAD

**Issue by Apexo01** [bivashy/MC-Auth-with-Link#39]
I would really like to be able to log in without a login if the player logged in through a licensed account, and if someone tried to log in without it on the same account, then ask for a password

I propose to add to the config such strings:
```yml
premium-auth-check: true  
premium-authentication-steps:
  - VK_LINK
  - TELEGRAM_LINK
  - GOOGLE_LINK
  - ENTER_SERVER
```

I would be very grateful if you could perform this
