### ISSUE TITLE
[Suggestion] Migration from other plugins

### ISSUE THREAD

**Issue by bivashy** [bivashy/MC-Auth-with-Link#60]
Migration from other plugins would be great. I think we could add **optional** field `migration-database` into `config.yml`. 
Probably it would look like this:
```yaml
migration-database:
  database-type: SQLITE
  host: localhost
  database: database_name
  username: username
  password: password
```

List of plugins to be able to migrate:
  - AuthMeReloaded
  - LimboAuth (With premium account support)
  - LibreLogin (With premium account support)
  - LoginSecurity
  - MoonVkAuth
  - BelkaAuth
  - DynamicBungeeAuth
